13 page popular films and film details
MaksKulykov/FilmCatalogNew pull request #7
Opened 2017-06-27 12:34 UTC by MaksKulykov

2017-07-03 15:07 UTC, fullstackdb requested changes

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/details-film-card/details-film-card.component.ts
> + */
удалите коментарии

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/details-film-card/details-film-card.component.ts
> +import {element} from "@angular/upgrade/src/angular_js";
добавьте пробелы

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/details-film-card/details-film-card.component.ts
> +import {element} from "@angular/upgrade/src/angular_js";
неиспользуемый импорт

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/details-film-card/details-film-card.component.ts
> +    getElements(data: Array<any>): string {
неиспользуемый метод.
Такого плана методы нужно выносить в сервис

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/details/details-film.component.ts
> +                    console.log(filmDetails);
удалить консоль логи

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/details/details-film.component.ts
> +    filmDetails: any[] = [];
совет:
опредилить модель/интерфейс вместо any

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/film.service.ts
> +        console.log(body);
удалить консоль логи

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/film.service.ts
> +            .catch((error: any)=> { return Observable.throw(error);});
форматировка кода

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/popular-film-card/popular-film-card.component.css
> +    margin-left: -13%;
минусовое значение в css гласит что что-то пошло не так)

старайтесь избегать их

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/popular-film-card/popular-film-card.component.html
> +            <p class="card-content">{{film.overview.slice(0,250) + '...'}}</p>
вынести в пайп переобразование дескрипшена

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/popular-film-card/popular-film-card.component.ts
> + */
удалить коментарии

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/popular/popular-film.component.ts
> +    filmPopularList: any[] = [];
использовать интерфес/модель вместо any

2017-07-03 15:07 UTC, fullstackdb commented on app/dashboard/popular/popular-film.component.ts
> +                        console.log(films);
удалить консоль логи

2017-07-03 15:07 UTC, fullstackdb commented on app/shared/navbar/navbar.component.ts
>          }
еще раз обдумать и переосмыслить логику этого метода

2017-07-10 10:07 UTC, MaksKulykov commented on app/dashboard/details-film-card/details-film-card.component.ts
> + */
done

2017-07-10 10:08 UTC, MaksKulykov commented on app/dashboard/details-film-card/details-film-card.component.ts
> +import {element} from "@angular/upgrade/src/angular_js";
done

2017-07-10 13:44 UTC, MaksKulykov commented on app/dashboard/details/details-film.component.ts
> +                    console.log(filmDetails);
done

2017-07-10 13:45 UTC, MaksKulykov commented on app/dashboard/film.service.ts
> +        console.log(body);
done

2017-07-10 13:46 UTC, MaksKulykov commented on app/dashboard/popular-film-card/popular-film-card.component.ts
> + */
done

2017-07-10 13:47 UTC, MaksKulykov commented on app/dashboard/popular/popular-film.component.ts
> +                        console.log(films);
done

2017-07-13 12:45 UTC, MaksKulykov commented on app/dashboard/details/details-film.component.ts
> +    filmDetails: any[] = [];
done

2017-07-13 12:45 UTC, MaksKulykov commented on app/dashboard/popular/popular-film.component.ts
> +    filmPopularList: any[] = [];
done

2017-07-13 13:19 UTC, MaksKulykov commented on app/dashboard/details-film-card/details-film-card.component.ts
> +    getElements(data: Array<any>): string {
ngOnInit удалил.
@fullstackdb Точно ли надо этот метод в данном конкретном случае выносить в сервис? Тут же никакого запроса нет, просто получаю данные из шаблона в виде массива и преобразовываю их в строку.

2017-07-13 13:25 UTC, MaksKulykov commented on app/dashboard/popular-film-card/popular-film-card.component.css
> +    margin-left: -13%;
@fullstackdb в данном конкретном случае все по плану) Задал размер(ширину) кнопки в процентах, и маргином отнял половину ширины в процентах, чтобы выровнять точно по центру.

2017-07-13 13:48 UTC, MaksKulykov commented on app/dashboard/popular-film-card/popular-film-card.component.html
> +            <p class="card-content">{{film.overview.slice(0,250) + '...'}}</p>
done

2017-07-13 16:56 UTC, MaksKulykov commented on app/dashboard/film.service.ts
> +            .catch((error: any)=> { return Observable.throw(error);});
done

2017-07-15 12:18 UTC, fullstackdb approved these changes

2017-07-18 07:25 UTC, merged